# custom path for swagger-ui
springdoc:
  swagger-ui:
    path: /swaggerui.html
    operationsSorter: alpha
    tagsSorter: alpha

  # custom path for api docs
  api-docs:
    path: /api-docs



#logging:
#  level:
#    root: debug

# https://www.youtube.com/watch?v=2o_3hjUPAfQ a partir desse vídeo